# Generated by Django 5.0.12 on 2025-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
    ]
